export enum DatasetSubjects {
  AGRICULTURAL_SCIENCE = 'Agricultural Sciences',
  ARTS_AND_HUMANITIES = 'Arts and Humanities',
  ASTRONOMY_AND_ASTROPHYSICS = 'Astronomy and Astrophysics',
  BUSINESS_AND_MANAGEMENT = 'Business and Management',
  CHEMISTRY = 'Chemistry',
  COMPUTER_AND_INFORMATION_SCIENCE = 'Computer and Information Science',
  EARTH_AND_ENVIRONMENTAL_SCIENCES = 'Earth and Environmental Sciences',
  ENGINEERING = 'Engineering',
  LAW = 'Law',
  MATHEMATICAL_SCIENCE = 'Mathematical Sciences',
  MEDICINE_HEALTH_AND_LIFE_SCIENCE = 'Medicine, Health and Life Sciences',
  PHYSICS = 'Physics',
  SOCIAL_SCIENCES = 'Social Sciences',
  OTHER = 'Other',
}
